window.IDLE_HUNTER_IMAGES = {
  "animals": {
    "House Sparrow": "assets/animals/house_sparrow.png",
    "American Crow": "assets/animals/american_crow.png",
    "Douglas Squirrel": "assets/animals/douglas_squirrel.png",
    "Cottontail Rabbit": "assets/animals/cottontail_rabbit.png",
    "Virginia Opossum": "assets/animals/virginia_opossum.png",
    "Striped Skunk": "assets/animals/striped_skunk.png",
    "Common Raccoon": "assets/animals/common_raccoon.png",
    "Black-Tailed Deer": "assets/animals/black_tailed_deer.png",
    "Red Fox": "assets/animals/red_fox.png",
    "Western Coyote": "assets/animals/western_coyote.png",
    "European Hare": "assets/animals/european_hare.png",
    "Ring-Necked Pheasant": "assets/animals/ring_necked_pheasant.png",
    "Eurasian Badger": "assets/animals/eurasian_badger.png",
    "Red Deer": "assets/animals/red_deer.png",
    "Eurasian Boar": "assets/animals/eurasian_boar.png",
    "Roe Deer": "assets/animals/roe_deer.png",
    "Tawny Owl": "assets/animals/tawny_owl.png",
    "Red Kite": "assets/animals/red_kite.png",
    "British Grey Wolf": "assets/animals/grey_wolf.png",
    "Eurasian Lynx": "assets/animals/eurasian_lynx.png",
    "Capercaillie": "assets/animals/capercaillie.png",
    "Willow Ptarmigan": "assets/animals/willow_ptarmigan.png",
    "Nordic Red Squirrel": "assets/animals/nordic_red_squirrel.png",
    "Mountain Reindeer": "assets/animals/mountain_reindeer.png",
    "Pine Marten": "assets/animals/pine_marten.png",
    "Eurasian Elk": "assets/animals/eurasian_elk.png",
    "Scandinavian Wolf": "assets/animals/grey_wolf.png",
    "Nordic Wolverine": "assets/animals/nordic_wolverine.png",
    "Boreal Lynx": "assets/animals/eurasian_lynx.png",
    "Nordic Brown Bear": "assets/animals/brown_bear.png",
    "Desert Jerboa": "assets/animals/desert_jerboa.png",
    "Rüppell&#x27;s Fox": "assets/animals/r_ppell_s_fox.png",
    "Sand Cat": "assets/animals/sand_cat.png",
    "Deathstalker Scorpion": "assets/animals/deathstalker_scorpion.png",
    "Saharan Horned Viper": "assets/animals/saharan_horned_viper.png",
    "Egyptian Vulture": "assets/animals/egyptian_vulture.png",
    "Dorcas Gazelle": "assets/animals/dorcas_gazelle.png",
    "Desert Monitor": "assets/animals/desert_monitor.png",
    "Addax Antelope": "assets/animals/addax_antelope.png",
    "Striped Hyena": "assets/animals/striped_hyena.png",
    "Atlantic Herring": "assets/animals/atlantic_herring.png",
    "Harbor Seal": "assets/animals/harbor_seal.png",
    "Atlantic Cod": "assets/animals/atlantic_cod.png",
    "Blue Lobster": "assets/animals/blue_lobster.png",
    "Striped Bass": "assets/animals/striped_bass.png",
    "Harbor Porpoise": "assets/animals/harbor_porpoise.png",
    "Atlantic Bluefin Tuna": "assets/animals/atlantic_bluefin_tuna.png",
    "Blue Shark": "assets/animals/blue_shark.png",
    "Leatherback Turtle": "assets/animals/leatherback_turtle.png",
    "North Atlantic Humpback": "assets/animals/north_atlantic_humpback.png",
    "Alpine Marmot": "assets/animals/alpine_marmot.png",
    "Black Grouse": "assets/animals/black_grouse.png",
    "Carpathian Red Deer": "assets/animals/red_deer.png",
    "Carpathian Boar": "assets/animals/eurasian_boar.png",
    "Carpathian Lynx": "assets/animals/eurasian_lynx.png",
    "Carpathian Wolf": "assets/animals/grey_wolf.png",
    "Carpathian Bear": "assets/animals/brown_bear.png",
    "European Bison": "assets/animals/european_bison.png",
    "Golden Jackal": "assets/animals/golden_jackal.png",
    "Ural Owl": "assets/animals/ural_owl.png",
    "Crab-Eating Macaque": "assets/animals/crab_eating_macaque.png",
    "Reticulated Python": "assets/animals/reticulated_python.png",
    "Malayan Tapir": "assets/animals/malayan_tapir.png",
    "Sun Bear": "assets/animals/sun_bear.png",
    "Clouded Leopard": "assets/animals/clouded_leopard.png",
    "Japanese Serow": "assets/animals/japanese_serow.png",
    "King Cobra": "assets/animals/king_cobra.png",
    "Bornean Orangutan": "assets/animals/bornean_orangutan.png",
    "Sunda Pangolin": "assets/animals/sunda_pangolin.png",
    "Indochinese Tiger": "assets/animals/indochinese_tiger.png",
    "Red Kangaroo": "assets/animals/red_kangaroo.png",
    "Emu": "assets/animals/emu.png",
    "Dingo": "assets/animals/dingo.png",
    "Frilled Lizard": "assets/animals/frilled_lizard.png",
    "Saltwater Crocodile": "assets/animals/saltwater_crocodile.png",
    "Perentie": "assets/animals/perentie.png",
    "Southern Cassowary": "assets/animals/southern_cassowary.png",
    "Wedge-Tailed Eagle": "assets/animals/wedge_tailed_eagle.png",
    "Common Wombat": "assets/animals/common_wombat.png",
    "Inland Taipan": "assets/animals/inland_taipan.png",
    "Anatolian Ground Squirrel": "assets/animals/anatolian_ground_squirrel.png",
    "Chukar Partridge": "assets/animals/chukar_partridge.png",
    "Bezoar Ibex": "assets/animals/bezoar_ibex.png",
    "Anatolian Leopard": "assets/animals/anatolian_leopard.png",
    "Anatolian Wolf": "assets/animals/grey_wolf.png",
    "Anatolian Hyena": "assets/animals/striped_hyena.png",
    "Caracal": "assets/animals/caracal.png",
    "Syrian Brown Bear": "assets/animals/syrian_brown_bear.png",
    "Griffon Vulture": "assets/animals/griffon_vulture.png",
    "Anatolian Golden Eagle": "assets/animals/anatolian_golden_eagle.png",
    "Kri-Kri Goat": "assets/animals/kri_kri_goat.png",
    "Hermann&#x27;s Tortoise": "assets/animals/hermann_s_tortoise.png",
    "Grecian Jackal": "assets/animals/grecian_jackal.png",
    "Grecian Boar": "assets/animals/grecian_boar.png",
    "Balkan Lynx": "assets/animals/balkan_lynx.png",
    "Grecian Wolf": "assets/animals/grecian_wolf.png",
    "Pindos Bear": "assets/animals/pindos_bear.png",
    "Aegean Vulture": "assets/animals/aegean_vulture.png",
    "Mediterranean Monk Seal": "assets/animals/mediterranean_monk_seal.png",
    "Olympian Eagle": "assets/animals/olympian_eagle.png",
    "Scarlet Ibis": "assets/animals/scarlet_ibis.png",
    "Green Iguana": "assets/animals/green_iguana.png",
    "Caribbean Flamingo": "assets/animals/caribbean_flamingo.png",
    "Hawksbill Turtle": "assets/animals/hawksbill_turtle.png",
    "Jamaican Boa": "assets/animals/jamaican_boa.png",
    "West Indian Manatee": "assets/animals/west_indian_manatee.png",
    "Cuban Crocodile": "assets/animals/cuban_crocodile.png",
    "Caribbean Reef Shark": "assets/animals/caribbean_reef_shark.png",
    "Queen Conch": "assets/animals/queen_conch.png",
    "Blue Marlin": "assets/animals/blue_marlin.png",
    "Lanternfish": "assets/animals/lanternfish.png",
    "Blackmouth Catshark": "assets/animals/blackmouth_catshark.png",
    "Giant Red Shrimp": "assets/animals/giant_red_shrimp.png",
    "Deep-Sea Anglerfish": "assets/animals/deep_sea_anglerfish.png",
    "Gulper Eel": "assets/animals/gulper_eel.png",
    "Mediterranean Sperm Whale": "assets/animals/mediterranean_sperm_whale.png",
    "Giant Squid": "assets/animals/giant_squid.png",
    "Bluntnose Sixgill Shark": "assets/animals/bluntnose_sixgill_shark.png",
    "Common Fangtooth": "assets/animals/common_fangtooth.png",
    "Colossal Squid": "assets/animals/colossal_squid.png",
    "Himalayan Marmot": "assets/animals/himalayan_marmot.png",
    "Bharal": "assets/animals/bharal.png",
    "Himalayan Tahr": "assets/animals/himalayan_tahr.png",
    "Himalayan Monal": "assets/animals/himalayan_monal.png",
    "Himalayan Griffon": "assets/animals/himalayan_griffon.png",
    "Red Panda": "assets/animals/red_panda.png",
    "Wild Yak": "assets/animals/wild_yak.png",
    "Bearded Vulture": "assets/animals/bearded_vulture.png",
    "Himalayan Snow Leopard": "assets/animals/himalayan_snow_leopard.png",
    "Tibetan Brown Bear": "assets/animals/tibetan_brown_bear.png"
  },
  "biomes": {
    "Village": "assets/biomes/village.png",
    "Forest": "assets/biomes/forest.png",
    "Woods": "assets/biomes/woods.png",
    "Small Desert": "assets/biomes/small_desert.png",
    "Large Desert": "assets/biomes/large_desert.png",
    "Tundra": "assets/biomes/tundra.png",
    "Jungle": "assets/biomes/jungle.png",
    "Swamp": "assets/biomes/swamp.png",
    "Volcanic Highlands": "assets/biomes/volcanic_highlands.png",
    "Cursed Ruins": "assets/biomes/cursed_ruins.png",
    "Rainbow Realm": "assets/biomes/rainbow.png",
    "Abyssal Depths": "assets/biomes/abyssal_depths.png",
    "Celestial Peaks": "assets/biomes/celestial_peaks.png"
  },
  "weapons": {
    "Bare Hands": "assets/weapons/bare-hands.png",
    "Slingshot": "assets/weapons/slingshot.png",
    "Hunting Knife": "assets/weapons/hunting-knife.png",
    "Spear": "assets/weapons/spear.png",
    "Shortbow": "assets/weapons/shortbow.png",
    "Longbow": "assets/weapons/longbow.png",
    "Crossbow": "assets/weapons/crossbow.png",
    "Musket": "assets/weapons/musket.png",
    "Hunting Rifle": "assets/weapons/hunting-rifle.png",
    "Shotgun": "assets/weapons/shotgun.png",
    "Sniper Rifle": "assets/weapons/sniper-rifle.png",
    "Tranq Gun": "assets/weapons/tranq-gun.png",
    "Plasma Caster": "assets/weapons/plasma-caster.png",
    "Gravity Trap": "assets/weapons/gravity-trap.png",
    "Soul Snare": "assets/weapons/soul-snare.png",
    "Void Bow": "assets/weapons/void-bow.png",
    "Celestial Lance": "assets/weapons/celestial-lance.png",
    "Mythic Net": "assets/weapons/mythic-net.png",
    "Dragon Cannon": "assets/weapons/dragon-cannon.png",
    "Cosmic RPG": "assets/weapons/cosmic-rpg.png",
    "Nuke Launcher": "assets/weapons/nuke-launcher.png"
  },
  "ammo": {
    "Wooden Arrow": "assets/ammo/wooden-arrow.png",
    "Iron Arrow": "assets/ammo/iron-arrow.png",
    "Enchanted Arrow": "assets/ammo/enchanted-arrow.png",
    "Phantom Arrow": "assets/ammo/phantom-arrow.png",
    "Crude Bolt": "assets/ammo/crude-bolt.png",
    "Steel Bolt": "assets/ammo/steel-bolt.png",
    "Gilded Bolt": "assets/ammo/gilded-bolt.png",
    "Venom Bolt": "assets/ammo/venom-bolt.png",
    "Lead Ball": "assets/ammo/lead-ball.png",
    "Hollow Point": "assets/ammo/hollow-point.png",
    "Silver Bullet": "assets/ammo/silver-bullet.png",
    "Void Round": "assets/ammo/void-round.png",
    "Basic Tranq": "assets/ammo/basic-tranq.png",
    "Potent Tranq": "assets/ammo/potent-tranq.png",
    "Exotic Serum": "assets/ammo/exotic-serum.png",
    "Void Serum": "assets/ammo/void-serum.png",
    "Charged Cell": "assets/ammo/charged-cell.png",
    "Overcharged Cell": "assets/ammo/overcharged-cell.png",
    "Plasma Core": "assets/ammo/plasma-core.png",
    "Singularity Cell": "assets/ammo/singularity-cell.png",
    "Fractured Shard": "assets/ammo/fractured-shard.png",
    "Pure Shard": "assets/ammo/pure-shard.png",
    "Void Shard": "assets/ammo/void-shard.png",
    "Eternal Shard": "assets/ammo/eternal-shard.png",
    "Star Slug": "assets/ammo/star-slug.png",
    "Nebula Round": "assets/ammo/nebula-round.png",
    "Celestial Core": "assets/ammo/celestial-core.png",
    "Eternal Cosmos": "assets/ammo/eternal-cosmos.png",
    "Nuke": "assets/ammo/nuke.png"
  }
};
